name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: warrenbuckley/Setup-Nuget
        path: setup-nuget
    - run: |
        sed -i 's(\"@actions/core\": \"\^1.0.0\"(\"@actions/core\": \"^1.2.6\"(' package.json
        cat package.json
        npm install
        npm build
      working-directory: setup-nuget
    - uses: ./setup-nuget
    #- uses: warrenbuckley/Setup-Nuget@v1
    - uses: actions/checkout@v2
      with:
        path: main
    - run: nuget restore TanukiColiseum.sln
      working-directory: main
    - uses: microsoft/setup-msbuild@v1
    - run: msbuild /t:"restore;clean;rebuild" /p:Configuration=Release /p:Platform="Any CPU"
      timeout-minutes: 5
      working-directory: main
    - run: |
        copy LICENSE TanukiColiseum\bin\Release\
        copy *.md TanukiColiseum\bin\Release\
        copy *.sfen TanukiColiseum\bin\Release\
      working-directory: main
    - id: datetime
      run: |
        echo "::set-output name=str::$(Get-Date -Format yyyyMMdd.hhmmss)"
    - uses: actions/upload-artifact@v2
      with:
          name: TanukiColiseum.${{ steps.datetime.outputs.str }}
          path: main\TanukiColiseum\bin\Release\
